name: Run Daily Task
on:
  workflow_dispatch:
  schedule:
    #cron表达式使用国际标准时间，任务在国际标准时间10:01执行（北京时间18:01）
    - cron: '1 10 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          acPassToken: ${{ secrets.acPassToken }}
          authKey: ${{ secrets.authKey }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          TELEGRAMBOTTOKEN: ${{ secrets.TELEGRAMBOTTOKEN }}
          TELEGRAMCHATID: ${{ secrets.TELEGRAMCHATID }}
          TZ: Asia/Shanghai
        run:
          mvn compile exec:java -Dexec.mainClass="com.zhuweitung.BananaMain" -Dexec.args="${acPassToken} ${authKey} ${SERVERPUSHKEY} ${TELEGRAMBOTTOKEN} ${TELEGRAMCHATID}"
